In [1]:
import numpy as np


# Creating an array with numpy

In [2]:
food = np.array(["pakora","samosa","raita"])
food

array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [4]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [5]:
type(price)

numpy.ndarray

In [6]:
type(food)

numpy.ndarray

In [7]:
len(price)

3

In [8]:
len(food)

3

In [9]:
price[2]

5

In [10]:
food[1]


'samosa'

In [11]:
food[0:]

array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [12]:
price.mean()

5.0

In [13]:
#zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [14]:
#ones
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [15]:
#empty
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [16]:
#range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
#range specify
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [19]:
#range specify with specific interval
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
#table of 5
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [29]:
# line space
np.linspace(0,100,num=10)


array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

# Array Sort

In [33]:
a = np.array([10,5,6,8,35,6,75,7,0.6,90.6,0.2,10])
a

array([10. ,  5. ,  6. ,  8. , 35. ,  6. , 75. ,  7. ,  0.6, 90.6,  0.2,
       10. ])

In [35]:
a.sort()
a

array([ 0.2,  0.6,  5. ,  6. ,  6. ,  7. ,  8. , 10. , 10. , 35. , 75. ,
       90.6])

# 2D array

In [38]:
b = np.array([[34,6,7,45,3],[65,3,6,3,45]])
b

array([[34,  6,  7, 45,  3],
       [65,  3,  6,  3, 45]])

In [48]:
c = np.array([[4,46,6,34,6],[5,7,34,7,4]])
c

array([[ 4, 46,  6, 34,  6],
       [ 5,  7, 34,  7,  4]])

In [49]:
np.concatenate((b,c), axis=0)

array([[34,  6,  7, 45,  3],
       [65,  3,  6,  3, 45],
       [ 4, 46,  6, 34,  6],
       [ 5,  7, 34,  7,  4]])

In [50]:
np.concatenate((b,c), axis=1)

array([[34,  6,  7, 45,  3,  4, 46,  6, 34,  6],
       [65,  3,  6,  3, 45,  5,  7, 34,  7,  4]])

In [51]:
bb = np.array([[[34,6,7,45,3],[65,3,6,3,45]],[[4,46,6,34,6],[5,7,34,7,4]],[[34,6,7,45,3],[65,3,6,3,45]]])
bb

array([[[34,  6,  7, 45,  3],
        [65,  3,  6,  3, 45]],

       [[ 4, 46,  6, 34,  6],
        [ 5,  7, 34,  7,  4]],

       [[34,  6,  7, 45,  3],
        [65,  3,  6,  3, 45]]])

In [52]:
bb.size

30

In [53]:
bb.shape

(3, 2, 5)

In [55]:
bb.ndim

3

In [56]:
#reshape
cc=np.arange(9) #3*3
cc

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [58]:
cc.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])